### PR TITLE
Add option for classes of lists that should not be cleared (by _clearEmpty)

### PR DESCRIPTION
**Pull request by ryfeng**

### CODE REVIEW

**Comment by mjsarfatti** [comment]
Interesting, might be a feature of a next update. Can you describe in detail your use case?

**Comment by ryfeng** [comment]
I used this as part of a binding in knockoutjs which will perform the necessary creation/deletion of list structures with the foreach binding. 
The _clearEmpty method interferes with that which leads to a discrepancy between what is being rendered and the internals of both of knockout and nestedSortable.

**Comment by mjsarfatti** [comment]
What if _doNotClear_ worked on a global scale? i.e. setting it to TRUE will not remove _any_ empty list.

**Comment by ryfeng** [comment]
That should also resolve my use case.
I see no application of doNotClear that would involve removing one list but retaining another, so setting a doNotClear to be a flag would work.

**Pull request merged**
