### PR TITLE
Additional functionality for constraining where nodes may be dropped

### PR DESCRIPTION
**Pull request by joekur**
Added option 'keepInContainer' to only allow nodes to be sorted within their original parent.

Added option 'maintainNestingLevel' to only allow nodes to be placed at the same nesting level as where they started.

Added option 'showErrorDiv' which decides whether a failed isAllowed() method shows an error placeholder or shows no change at all.

isAllowed() now takes the current item instead of the current placeholder.

I hope these changes may help :)

### CODE REVIEW

**Comment by cidic** [comment]
I think maintain nesting level would be much more useful if it were like "disableNesting" where you can set it per item with a css class.

**Comment by mjsarfatti** [comment]
Quoting cidic comment.

keepInContainer could be useful, but isn't it a regular Sortable then?

Another question, why would you not want the error div to be shown?

And lastly :) why do you need the current item instead of the placeholder in the isAllowed function (I'm not saying it's a bad idea, just trying to understand)?

**Comment by joekur** [comment]
- keepInContainer - Yes, perhaps you are right
- Error divs - Well in my case, I wanted to maintain nesting level on my list, because I had distinct types of objects which had a hierarchical relationship (for example, a learning course has many lessons, which have many sections, which have many review questions, ...). This I eventually ended up putting into the code itself instead of using the isAllowed function. And it didn't make sense to me from a UX standpoint to give the user visual feedback that they couldn't nest, for example, a course underneath a review question. So had I tried to use the isAllowed() function, I would have liked the option to not show the error divs.
- Current item in isAllowed - Following from the use case I mentioned, had I tried to implement an isAllowed() function to maintain nesting depth, I would need to know the object that I was moving, and the parent I was trying to move it under. As I understand, your current implementation does not give the function any knowledge of the node being dragged? To me, the exact drop location does not seem so important, given you already have access to the parent. But of course, it would be possible to pass all 3 objects to the function.

And regarding the comment about using a css class for disableNesting, I would be open to contributing to that feature, if you agree. In my use case however, I didn't need to specify specific nodes to apply the restriction to.

**Comment by cidic** [comment]
I have a use case where nodes can have very specific rules. some can only be root, some can not change their parent but change their order. some cannot have children. etc.

**Comment by webrod** [comment]
Hi,

I'm not sure to understand whether this has already implemented, or not.
For instance you say "isAllowed() now takes the current item instead of the current placeholder."
But it's not the case right?
I have no means to get any information about the item that is moving.

Is it correct?

Thanks
rod

**Comment by hotpot** [comment]
@webrod - these changes are not implemented in the main branch. The develop branch does not currently exist, for added confusion. If you don't understand the branches, read up on how GitHub works.

There are actually a few requests that suggest code for actually having the item and parent in isAllowed() - the issue has come up several times.

I do think it is misleading to have the placeholder as the 'item', so I use isAllowed(parent,placeholder).

However, you _are_ able to get information about the item that is moving.

You can pick up the item yourself within the function with
item = ($('#list-container').data().nestedSortable.currentItem);
or similar. (the # should match what you put .nestedSortable on)

**Comment by webrod** [comment]
thanks you very much!
Then I did this:
isAllowed: function(parent, item) { 
  return !($('ol.sortable').data().nestedSortable.currentItem).hasClass("no-move"); 
}

So I can now add the class "no-move" to any items so they cannot be moved :-)

Thanks you again
Rod

**Comment by cidic** [comment]
this simple change allowed me to do everything I needed and would not break existing implementations as it just adds a param to the isAllowed function. Now you have isAllowed(parentItem, placeholder, item){ ... }

original line 403 : if (!o.isAllowed(parentItem, this.placeholder) ||
my line 403 : if (!o.isAllowed(parentItem, this.placeholder, this) ||

**Comment by mjsarfatti** [comment]
Back to the original question for a moment:
- Error divs: I thought a lot about this, but I'm sorry I will not implement this feature, for two reasons. First of all, I want to keep the plugin as light as possible and I can't include every single feature a developer might need (often, 'one' developer); secondly, most custom behaviors can be obtained using the provided events (update, stop etc.).
- isAllowed: I'm working at a bigger update at the moment (a tree-like nestedSortable, with branches, collapsing functionality and so on). That update will definitely include the modified isAllowed as cidic suggested.

About the 'develop' branch not being here anymore: That scheme ended up not working well enough for me, so i switched back to having a single 'master' branch, and opening from time to time feature-based branches as needed. Sorry about the confusion!

**Comment by cidic** [comment]
mjsarfatti: I agree about the error divs. It was very easy to implement error messages for isAllowed. I opted to have the messages displayed in the placeholder. It looked nice and guaranteed that the message would be visible to the user no matter how long the list was. I think this would be nice to have an example of in the readme. I can write it up if you are interested.

I have written some nice branch collapse functionality for my tree implementation if you are interested in some help. I really like this plugin and would be interested in helping with further development, just let me know. In your update I would very much like to see more comments in the code.

**Comment by mjsarfatti** [comment]
There was an idea of having an 'example' section in the documentation. It could be like "example 1: basic functionality"; "example 2: error messages"; "example 3: ...". It would be great if you could write something about your solution.

About the branch collapse, I already have a 99% working example, but feel free to send along your own solution. I will push to github my working copy anytime in the next week. Thanks for the offer!

And I will definitely comment more the code in the next version.

**Comment by AlterHaudegen** [comment]
Adding

item = $('ol.sortable').data().nestedSortable.currentItem;

inside isAllowed solved my issues.

**Pull request closed without merging**
