### PR TITLE
Proper child level counting, and _mouseStop fallback.

### PR DESCRIPTION
**Pull request by Bananattack**
Fixed a major issue where the depth of a list item's subtree was miscalculated (with the `_getChildLevels(...)` method). This meant that occasionally top-level elements would be kicked out of their `<ol>` list container because they'd exceed their nestedSortable's max levels, which was _pretty_ broken.

As an example, this configuration would not be accepted if the max levels were 3, because the depth of this subtree was miscalculated as 4, instead of 3:

```
* A
  * B
    * C
  * D
    * E
```

This was considered depth 5:

```
* A
  * B
    * C
  * D
    * E
  * F
    * G
```

So as you can see, using `:first-child` is not the correct way to check for the depth of the DOM tree. I made this a recursive DOM traversal instead, and it works. I don't imagine that performance will be hurt too much.

Also added a fallback to the `_mouseStop` function such that it should be less likely to accidentally insert outside the sortable list.

These fixes should hopefully improve the usability of this plugin.

Thanks,

-- Andrew G. Crowell

### CODE REVIEW

**Comment by Bananattack** [comment]
Ugh, I forgot to remove one debug text from the placeholder div. I'm on it.

**Comment by Bananattack** [comment]
Okay debug text removed, it should ready for review now.

**Comment by mjsarfatti** [comment]
Wow, thanks for spotting and fixing this issue! 

One question: is the `_mouseStop` fallback necessary, or just a safety measure?

And a side note: `$(this.placeholder[0])` is in fact equivalent to `this.placeholder`.

**Comment by Bananattack** [comment]
Oh! Good eyes, I didn't dig around much to see where `this.placeholder` was initialized.

And yeah, the `_mouseStop` fallback was an extra safety measure, it can probably be discarded, if you're not too worried about that. I originally did it before I discovered the child-depth problem.

**Comment by mjsarfatti** [comment]
I prefer to let possible errors be as visible as possible. I reverted the `_mouseStop` function as it was before and made a few (mostly aesthetic) improvements to your fix. Thanks again!

**Pull request merged**
